import AdmZip from "adm-zip";
import { fetchPvTrainLink } from "./datamall";
import { RACHEL_JOURNEY } from "./rachel";
import { getJSON, setJSON } from "./store";

export type BaselineLabel = "low" | "typical" | "high" | "unknown";

// Several of Rachel's stations turn out to be interchanges in this dataset —
// more than expected going in. PV/Train merges an interchange's codes into
// one PT_CODE joined by "/" (confirmed from the real response, not the API
// guide's own example, which uses "-" and turned out not to match: real
// rows look like "EW12/DT14", "NS25/EW13", "EW2/DT32" — note the component
// order isn't consistent, and even Tampines (EW2) and Paya Lebar (EW8) are
// merged, which the API guide gives no hint of). Rather than hardcode a
// mapping we'd have to get exactly right for every current and future
// interchange, split each row's PT_CODE on "/" and match components against
// Rachel's station codes directly — robust to any interchange shape.
function pvCodeComponents(ptCode: string): string[] {
  return ptCode.split("/").map((c) => c.trim());
}

interface BaselineRecord {
  yearMonth: string;
  labelByStationHour: Record<string, BaselineLabel[]>;
  fetchedAt: string;
}

const STORE_KEY = "pvTrainBaseline:v1";

function targetYearMonth(): string {
  // PV/Train's previous-month data is generated by the 10th of the
  // following month (API guide §2.8) — before that, even "last month" may
  // not exist yet, so fall back one month further in that window.
  const now = new Date();
  const monthsBack = now.getUTCDate() < 10 ? 2 : 1;
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - monthsBack, 1));
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
}

async function downloadAndParseCsv(link: string): Promise<string> {
  const res = await fetch(link);
  if (!res.ok) throw new Error(`PV/Train download ${res.status} ${res.statusText}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const zip = new AdmZip(buffer);
  const entry = zip.getEntries().find((e) => e.entryName.toLowerCase().endsWith(".csv"));
  if (!entry) throw new Error("PV/Train ZIP contained no .csv file");
  return entry.getData().toString("utf-8");
}

// Quantile-based, not a model: within one station's own 24 weekday hours,
// the busiest third of hours is "high", the quietest third "low", the
// middle "typical". Comparing across stations wouldn't be fair (a big
// interchange is just bigger than a small station in absolute taps); this
// only ever compares a station's hour against its own day.
function labelsForStation(volumes: number[]): BaselineLabel[] {
  const known = volumes.filter((v) => v > 0);
  if (known.length === 0) return volumes.map(() => "unknown");
  const sorted = [...known].sort((a, b) => a - b);
  const lowCut = sorted[Math.floor(sorted.length / 3)];
  const highCut = sorted[Math.floor((sorted.length * 2) / 3)];
  return volumes.map((v) => {
    if (v <= 0) return "unknown";
    if (v <= lowCut) return "low";
    if (v >= highCut) return "high";
    return "typical";
  });
}

function parseCsv(csv: string): Record<string, number[]> {
  const byStation: Record<string, number[]> = {};
  const rachelCodes = new Set(RACHEL_JOURNEY.stations.map((s) => s.code));

  for (const line of csv.split("\n")) {
    const cols = line.split(",").map((c) => c.trim());
    if (cols.length < 7) continue;
    const [, dayType, timePerHour, ptType, ptCode, tapIn, tapOut] = cols;
    if (ptType !== "TRAIN" || dayType !== "WEEKDAY") continue;

    const matchedCode = pvCodeComponents(ptCode).find((c) => rachelCodes.has(c));
    if (!matchedCode) continue;

    const hour = Number(timePerHour);
    const volume = Number(tapIn) + Number(tapOut);
    if (!Number.isFinite(hour) || !Number.isFinite(volume)) continue;

    if (!byStation[matchedCode]) byStation[matchedCode] = new Array(24).fill(0);
    byStation[matchedCode][hour] = volume;
  }
  return byStation;
}

async function fetchAndBuildBaseline(yearMonth: string): Promise<Record<string, BaselineLabel[]>> {
  const link = await fetchPvTrainLink(yearMonth);
  const csv = await downloadAndParseCsv(link);
  const byStationCode = parseCsv(csv);

  const labels: Record<string, BaselineLabel[]> = {};
  for (const station of RACHEL_JOURNEY.stations) {
    const volumes = byStationCode[station.code] ?? new Array(24).fill(0);
    labels[station.code] = labelsForStation(volumes);
  }
  return labels;
}

export async function getBaseline(): Promise<{
  labelByStationHour: Record<string, BaselineLabel[]>;
  fetchedAt: string | null;
  error: string | null;
}> {
  const yearMonth = targetYearMonth();
  const cached = await getJSON<BaselineRecord>(STORE_KEY);

  // Only re-fetch if we've never fetched, or the target month rolled over
  // since (this data changes monthly, not per-request).
  if (cached && cached.yearMonth === yearMonth) {
    return { labelByStationHour: cached.labelByStationHour, fetchedAt: cached.fetchedAt, error: null };
  }

  try {
    const labelByStationHour = await fetchAndBuildBaseline(yearMonth);
    const record: BaselineRecord = { yearMonth, labelByStationHour, fetchedAt: new Date().toISOString() };
    await setJSON(STORE_KEY, record);
    return { labelByStationHour, fetchedAt: record.fetchedAt, error: null };
  } catch (err) {
    // keep serving last month's cached baseline rather than going blank —
    // it's still a reasonable approximation for one month
    if (cached) {
      return {
        labelByStationHour: cached.labelByStationHour,
        fetchedAt: cached.fetchedAt,
        error: err instanceof Error ? err.message : String(err),
      };
    }
    return { labelByStationHour: {}, fetchedAt: null, error: err instanceof Error ? err.message : String(err) };
  }
}
